# Generated by Django 2.1.4 on 2018-12-08 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('FID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('PID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Perishable', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=100)),
                ('OnHold', models.PositiveIntegerField()),
                ('MinQty', models.PositiveIntegerField()),
                ('Qty', models.PositiveIntegerField()),
                ('OrderReq', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Approved', models.BooleanField(null=True)),
                ('Delivered', models.BooleanField(default=False)),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('DeliveryDate', models.DateField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact', to='StationaryAPI.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Item')),
                ('ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Order')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('OrderID', models.BigAutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('DeliveryDate', models.DateField()),
                ('Paid', models.BooleanField(default=False)),
                ('Delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Item')),
                ('sord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.SupplyOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('VID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('DealsIn', models.ManyToManyField(related_name='deal', through='StationaryAPI.Dealer', to='StationaryAPI.Item')),
            ],
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='items',
            field=models.ManyToManyField(related_name='supplyorditems', through='StationaryAPI.SupplyOrderItems', to='StationaryAPI.Item'),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vend', to='StationaryAPI.Vendor'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orditems', through='StationaryAPI.OrderItems', to='StationaryAPI.Item'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='CurrIt',
            field=models.ManyToManyField(related_name='curritems', through='StationaryAPI.CurrentItems', to='StationaryAPI.Item'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Item'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='ven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Vendor'),
        ),
        migrations.AddField(
            model_name='currentitems',
            name='fac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Faculty'),
        ),
        migrations.AddField(
            model_name='currentitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Item'),
        ),
    ]
