# Generated by Django 2.1.4 on 2018-12-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryAPI', '0003_auto_20181208_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DeliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='DeliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
