# Generated by Django 2.1.4 on 2018-12-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryAPI', '0004_auto_20181208_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentitems',
            name='fac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facn', to='StationaryAPI.Faculty'),
        ),
        migrations.AlterField(
            model_name='currentitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemn', to='StationaryAPI.Item'),
        ),
    ]
