# Generated by Django 2.1.4 on 2018-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryAPI', '0005_auto_20181208_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
