# Generated by Django 2.1.4 on 2018-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryAPI', '0006_vendor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
