# Generated by Django 2.1.4 on 2018-12-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryAPI', '0007_auto_20181210_1839'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currentitems',
            unique_together={('fac', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='dealer',
            unique_together={('ven', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitems',
            unique_together={('ord', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='supplyorderitems',
            unique_together={('sord', 'item')},
        ),
    ]
